// <auto-generated />
namespace ELearning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class user04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user04));
        
        string IMigrationMetadata.Id
        {
            get { return "201504171841300_user04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
