// <auto-generated />
namespace ELearning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CustomProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201504170449569_CustomProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
