//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreenLightFeaturesEntities : DbContext
    {
        public GreenLightFeaturesEntities()
            : base("name=GreenLightFeaturesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<CMSPage> CMSPage { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseClass> CourseClass { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<ExamQuestion> ExamQuestion { get; set; }
        public virtual DbSet<ExamType> ExamType { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<TrainingBase> TrainingBase { get; set; }
        public virtual DbSet<EvaluationType> EvaluationTypeSet { get; set; }
    }
}
