//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FilePath { get; set; }
        public System.DateTime PubDate { get; set; }
        public int Order { get; set; }
        public int CourseClassId { get; set; }
    
        public virtual CourseClass CourseClass { get; set; }
    }
}
