//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public Attendance()
        {
            this.IsInstructorPresent = false;
        }
    
        public int Id { get; set; }
        public string StudentIds { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public bool isHoliday { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isAllPresent { get; set; }
        public int CourseClassId { get; set; }
        public bool IsInstructorPresent { get; set; }
    
        public virtual CourseClass CourseClass { get; set; }
    }
}
