//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseClass
    {
        public CourseClass()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Attachment = new HashSet<Attachment>();
            this.Exam = new HashSet<Exam>();
        }
    
        public int Id { get; set; }
        public int TrainingBaseId { get; set; }
        public int CourseId { get; set; }
        public int InstructorId { get; set; }
        public bool Status { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string StudentIds { get; set; }
        public string Title { get; set; }
        public string ClassDates { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Course Course { get; set; }
        public virtual TrainingBase TrainingBase { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<Exam> Exam { get; set; }
    }
}
