//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.Evaluation = new HashSet<Evaluation>();
            this.ExamQuestion = new HashSet<ExamQuestion>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsPublished { get; set; }
        public int ExamTypeId { get; set; }
        public string MaxGrade { get; set; }
        public int UserId { get; set; }
        public int Duration { get; set; }
        public bool IsDeleted { get; set; }
        public int CourseClassId { get; set; }
    
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual ICollection<ExamQuestion> ExamQuestion { get; set; }
        public virtual CourseClass CourseClass { get; set; }
    }
}
