//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.ExamQuestion = new HashSet<ExamQuestion>();
        }
    
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public int CorrectAnswer { get; set; }
        public string AnswerData { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<ExamQuestion> ExamQuestion { get; set; }
    }
}
